services:
  docs:
    image: work_tools_local_docs
    container_name: work_tools_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./work_tools:/app/work_tools:z
    ports:
      - '9000:9000'
    command: /start-docs
